### ISSUE TITLE
`pyproject.toml` fails at `Getting requirements to build wheel` stage

### ISSUE THREAD

**Issue by paulora2405** [GeminiLight/virne#5]
I've been following this project for a few weeks now, and I was excited to see the addition of a `pyproject.toml` file recently.

Unfortunately, when I try to setup the project via `pip install .` in the root of the repo, I get the following error:

```bash
Defaulting to user installation because normal site-packages is not writeable
Processing /*REDACTED*/virne
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /tmp/pip-build-env-ccn_0cd0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running egg_info
      writing virne.egg-info/PKG-INFO
      writing dependency_links to virne.egg-info/dependency_links.txt
      writing requirements to virne.egg-info/requires.txt
      writing top-level names to virne.egg-info/top_level.txt
      reading manifest file 'virne.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'virne.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ccn_0cd0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ccn_0cd0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ccn_0cd0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 29, in <module>
      ValueError
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Could you try to take a look at this problem? And if you are able to setup the project in your machine, could you provide what version of Python and Pip are you using? I'm on Python 3.10.9, and Pip 23.0

Thanks in advance.

**Comment by GeminiLight** [comment]
Thank you for your attention. The completing yaml file about project requirements is still a developing feature. Instead, the command `bash install.sh` is available for setting the Python environment this repo requires.
