### ISSUE TITLE
AttributeError: 'PhysicalNetwork' object has no attribute '_adj'

### ISSUE THREAD

**Issue by dzljoy** [GeminiLight/virne#8]
Hello! 我在运行项目main.py时出现如下报错，可以看下是什么原因吗？

C:\Users\Administrator\virne\Scripts\python.exe C:/Git2023/virne/main.py 

--------------------    Start     --------------------

Use grc_rank Solver (Type = heuristic)...

dataset/p_net\100-waxman_[0.5-0.2]-cpu_[50-100]-max_cpu_None-bw_[50-100]-max_bw_None-ltc_[0.0-1.0]
*** Generate Physical Network from setting
Create VNR Simulator from setting
Traceback (most recent call last):
  File "C:\Git2023\virne\main.py", line 47, in <module>
    run(config)
  File "C:\Git2023\virne\main.py", line 15, in run
    scenario = BasicScenario.from_config(Env, Solver, config)
  File "C:\Git2023\virne\base\scenario.py", line 52, in from_config
    env = Env(p_net, v_net_simulator, controller, recorder, counter, **vars(config))
  File "C:\Git2023\virne\base\environment.py", line 336, in __init__
    super(SolutionStepEnvironment, self).__init__(p_net, v_net_simulator, controller, recorder, counter, **kwargs)
  File "C:\Git2023\virne\base\environment.py", line 20, in __init__
    self.init_p_net = copy.deepcopy(p_net)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\copy.py", line 272, in _reconstruct
    y.__setstate__(state)
  File "C:\Users\Administrator\virne\lib\site-packages\networkx\classes\reportviews.py", line 994, in __setstate__
    self._adjdict = G._succ if hasattr(G, "succ") else G._adj
AttributeError: 'PhysicalNetwork' object has no attribute '_adj'

Process finished with exit code 1

**Comment by GeminiLight** [comment]
可能是您的Networkx包的版本不太对，可以先试试重装下

**Comment by dzljoy** [comment]
> 可能是您的Networkx包的版本不太对，可以先试试重装下
您好，我的Networkx包是2.6.3的，请问要装什么版本的呢？

**Comment by dzljoy** [comment]
非常感谢您的解答，将Networkx包更新为3.1版本后，这个报错就消失了。
